# Generated by Django 5.2.17 on 2026-08-22 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência')], max_length=15, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Valor absoluto da movimentação (ajustes usam sinal).', max_digits=12, verbose_name='quantidade')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('movimento_par', models.ForeignKey(blank=True, help_text='Movimento vinculado (saída/entrada de uma transferência).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartes', to='stock.movimentoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='catalog.produto', verbose_name='produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.unidade', verbose_name='unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantidade')),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantidade mínima')),
                ('quantidade_bloqueada', models.DecimalField(decimal_places=2, default=0, help_text='Reservada para pedidos em andamento; não está disponível.', max_digits=12, verbose_name='quantidade bloqueada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='catalog.produto', verbose_name='produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoques',
                'constraints': [models.UniqueConstraint(fields=('produto', 'unidade'), name='uniq_estoque_produto_unidade'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='estoque_quantidade_nao_negativa'), models.CheckConstraint(condition=models.Q(('quantidade_bloqueada__gte', 0)), name='estoque_bloqueada_nao_negativa'), models.CheckConstraint(condition=models.Q(('quantidade__gte', models.F('quantidade_bloqueada'))), name='estoque_bloqueada_dentro_do_saldo')],
            },
        ),
    ]
