# Generated by Django 5.2.17 on 2026-08-23 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_interacaovendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('cadastro', 'Cadastro e operação da conta'), ('compras', 'Execução de pedidos e entregas'), ('marketing', 'Comunicações de marketing')], max_length=20, verbose_name='finalidade')),
                ('versao_politica', models.CharField(default='1.0', max_length=12, verbose_name='versão da política')),
                ('aceito', models.BooleanField(default=True, verbose_name='aceito')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='customers.cliente', verbose_name='cliente/titular')),
            ],
            options={
                'verbose_name': 'consentimento LGPD',
                'verbose_name_plural': 'consentimentos LGPD',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso aos dados'), ('correcao', 'Correção de dados'), ('exportacao', 'Exportação dos dados'), ('exclusao', 'Exclusão dos dados')], max_length=12, verbose_name='tipo')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluída'), ('recusada', 'Recusada')], default='aberta', max_length=10, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('aberta_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('prazo_limite', models.DateField(verbose_name='prazo limite')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_lgpd', to='customers.cliente', verbose_name='titular')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_lgpd_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'solicitação do titular',
                'verbose_name_plural': 'solicitações dos titulares',
                'ordering': ['-aberta_em'],
            },
        ),
    ]
