# Generated by Django 5.2.17 on 2026-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('cidade', models.CharField(max_length=80, verbose_name='cidade')),
                ('tipo', models.CharField(choices=[('loja', 'Loja'), ('deposito', 'Depósito')], default='loja', max_length=20, verbose_name='tipo')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['nome'],
            },
        ),
    ]
