# Generated by Django 5.2.17 on 2026-08-22 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=60, verbose_name='ação')),
                ('objeto_tipo', models.CharField(max_length=80, verbose_name='tipo do objeto')),
                ('objeto_id', models.CharField(max_length=50, verbose_name='id do objeto')),
                ('antes', models.JSONField(blank=True, null=True, verbose_name='antes')),
                ('depois', models.JSONField(blank=True, null=True, verbose_name='depois')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
