# Generated by Django 5.2.17 on 2026-08-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque baixo'), ('pago_sem_nfe', 'Pedido pago sem NF-e'), ('pagamento_pendente', 'Pagamento pendente há muito tempo'), ('possivel_recompra', 'Possível recompra')], db_index=True, max_length=30, verbose_name='tipo')),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('alerta', 'Atenção'), ('erro', 'Crítico')], default='alerta', max_length=10, verbose_name='severidade')),
                ('mensagem', models.CharField(max_length=255, verbose_name='mensagem')),
                ('objeto_tipo', models.CharField(blank=True, help_text='Label do modelo relacionado (ex.: app_label.ModelName).', max_length=60, verbose_name='tipo do objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='id do objeto')),
                ('lido', models.BooleanField(default=False, verbose_name='lido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
