# Generated by Django 5.2.17 on 2026-08-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('estoque_baixo', 'Estoque baixo'), ('pago_sem_nfe', 'Pedido pago sem NF-e'), ('pagamento_pendente', 'Pagamento pendente há muito tempo'), ('possivel_recompra', 'Possível recompra'), ('fiscal_erro', 'Erro na emissão fiscal'), ('fiscal_documento', 'Documento fiscal inválido')], db_index=True, max_length=30, verbose_name='tipo'),
        ),
    ]
