# Generated by Django 5.2.17 on 2026-08-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de envio'), ('autorizada', 'Autorizada'), ('erro', 'Erro')], default='pendente', max_length=12, verbose_name='status')),
                ('origem', models.CharField(choices=[('api', 'Integração Bling'), ('manual', 'Registro manual')], default='api', max_length=10, verbose_name='origem')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, verbose_name='chave de acesso')),
                ('link_documento', models.URLField(blank=True, max_length=300, verbose_name='link do documento/XML-DANFE')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_fiscal', to='sales.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
            },
        ),
    ]
