# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.core.validators
from django.db import migrations, models

import customers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('operacional', 'Operacional'), ('transporte', 'Transporte'), ('armazenagem', 'Armazenagem'), ('marketing', 'Marketing'), ('impostos', 'Impostos'), ('outros', 'Outros')], max_length=20, verbose_name='categoria')),
                ('tipo', models.CharField(blank=True, max_length=80, verbose_name='tipo')),
                ('fornecedor', models.CharField(blank=True, max_length=120, verbose_name='fornecedor')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=18, validators=[customers.validators.validar_cnpj], verbose_name='CNPJ do fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='unica', max_length=10, verbose_name='recorrência')),
                ('data', models.DateField(verbose_name='data')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-data'],
            },
        ),
    ]
