# Generated by Django 5.2.17 on 2026-08-22 21:12

from django.db import migrations, models

import customers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], max_length=10, verbose_name='tipo')),
                ('documento', models.CharField(max_length=18, unique=True, validators=[customers.validators.DocumentoValidator()], verbose_name='CPF/CNPJ')),
                ('categoria', models.CharField(choices=[('atacado', 'Atacado'), ('varejo', 'Varejo')], default='varejo', max_length=10, verbose_name='categoria')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('logradouro', models.CharField(blank=True, max_length=120, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='número')),
                ('bairro', models.CharField(blank=True, max_length=60, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=60, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('preferencia', models.TextField(blank=True, help_text='Produtos habituais, forma de pagamento preferida etc.', verbose_name='preferência de compra')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
