# Generated by Django 5.2.17 on 2026-08-22 22:16

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_logauditoria'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoWebhookEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(default='mercadopago', max_length=30, verbose_name='provedor')),
                ('referencia_externa', models.CharField(db_index=True, help_text='Identificador do recurso notificado (ex.: payment_id).', max_length=120, verbose_name='referência externa')),
                ('payload', models.JSONField(verbose_name='payload bruto')),
                ('processado', models.BooleanField(default=False, verbose_name='processado')),
                ('resultado', models.CharField(blank=True, max_length=255, verbose_name='resultado')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='número')),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Permite acompanhar o pedido sem expor IDs sequenciais.', unique=True, verbose_name='token de acesso')),
                ('canal', models.CharField(choices=[('loja', 'Loja online'), ('vendedor', 'Vendedor')], default='loja', max_length=10, verbose_name='canal')),
                ('modalidade', models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada na unidade')], max_length=10, verbose_name='modalidade')),
                ('logradouro', models.CharField(blank=True, max_length=120, verbose_name='logradouro')),
                ('numero_endereco', models.CharField(blank=True, max_length=10, verbose_name='número')),
                ('bairro', models.CharField(blank=True, max_length=60, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=60, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('contato_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone de contato')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='frete')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pagamento_pendente', 'Pagamento pendente'), ('pago', 'Pago'), ('em_separacao', 'Em separação'), ('pronto_para_entrega', 'Pronto para entrega'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('falhou', 'Falhou')], db_index=True, default='aguardando_pagamento', max_length=25, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='customers.cliente', verbose_name='cliente')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.unidade', verbose_name='unidade de atendimento')),
                ('usuario_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(default='mercadopago', max_length=30, verbose_name='provedor')),
                ('preferencia_id', models.CharField(blank=True, max_length=60, verbose_name='ID da preferência')),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='ID externo do pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='sales.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=120, verbose_name='nome do produto')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço online capturado no momento do checkout.', max_digits=12, verbose_name='preço unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalog.produto', verbose_name='produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
